##----------CONTROL--------------------
CONTROL_FOC = 0x40 # FROM HLS 
CONTROL_FOC_MODE = CONTROL_FOC + 0x00
CONTROL_ANGLE_SHIFT = CONTROL_FOC + 0x04
FILT_A = CONTROL_FOC + 0x08
FILT_B = CONTROL_FOC + 0x0C
RPM_SP = CONTROL_FOC + 0x10
RPM_KP = CONTROL_FOC + 0x14
RPM_KI = CONTROL_FOC + 0x18
TORQUE_SP = CONTROL_FOC + 0x1C
TORQUE_KP = CONTROL_FOC + 0x20
TORQUE_KI = CONTROL_FOC + 0x24
FLUX_SP = CONTROL_FOC + 0x28
FLUX_KP = CONTROL_FOC + 0x2C
FLUX_KI = CONTROL_FOC + 0x30
ANGLE = CONTROL_FOC + 0x34
LOG_MODE = CONTROL_FOC + 0x38

##----------LOGGER--------------------
IALPHA_IBETA_RPM_ANGLE = 1
ID_IQ_RPM = 2
VD_VQ_RPM = 3
VALPHA_VBETA_RPM = 4
VA_VB_VC_RPM = 5
PWMA_PWMB_PWMC_RPM = 6
