#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_local_block", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("A_TDATA", 80, hls_in, 0, "axis", "in_data", 1),
	Port_Property("A_TVALID", 1, hls_in, 3, "axis", "in_vld", 1),
	Port_Property("A_TREADY", 1, hls_out, 3, "axis", "in_acc", 1),
	Port_Property("A_TKEEP", 10, hls_in, 1, "axis", "in_data", 1),
	Port_Property("A_TSTRB", 10, hls_in, 2, "axis", "in_data", 1),
	Port_Property("A_TLAST", 1, hls_in, 3, "axis", "in_data", 1),
	Port_Property("B_TDATA", 64, hls_out, 4, "axis", "out_data", 1),
	Port_Property("B_TVALID", 1, hls_out, 7, "axis", "out_vld", 1),
	Port_Property("B_TREADY", 1, hls_in, 7, "axis", "out_acc", 1),
	Port_Property("B_TKEEP", 8, hls_out, 5, "axis", "out_data", 1),
	Port_Property("B_TSTRB", 8, hls_out, 6, "axis", "out_data", 1),
	Port_Property("B_TLAST", 1, hls_out, 7, "axis", "out_data", 1),
	Port_Property("C_TDATA", 64, hls_out, 8, "axis", "out_data", 1),
	Port_Property("C_TVALID", 1, hls_out, 11, "axis", "out_vld", 1),
	Port_Property("C_TREADY", 1, hls_in, 11, "axis", "out_acc", 1),
	Port_Property("C_TKEEP", 8, hls_out, 9, "axis", "out_data", 1),
	Port_Property("C_TSTRB", 8, hls_out, 10, "axis", "out_data", 1),
	Port_Property("C_TLAST", 1, hls_out, 11, "axis", "out_data", 1),
	Port_Property("s_axi_control_r_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_r_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_r_AWADDR", 8, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_r_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_r_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_r_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_r_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_r_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_r_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_r_ARADDR", 8, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_r_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_r_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_r_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_r_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_r_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_r_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_r_BRESP", 2, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "foc_frontend";
