# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mklab/workspace/iiot-eddp/Vitis/zcu104_foc_pkg/vivado/output/temp/vv/k26_foc.srcs/sources_1/bd/design_1/ip/design_1_psu_0/design_1_psu_0.xci
# IP: The module: 'design_1_psu_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mklab/workspace/iiot-eddp/Vitis/zcu104_foc_pkg/vivado/output/temp/vv/k26_foc.gen/sources_1/bd/design_1/ip/design_1_psu_0/design_1_psu_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_psu_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/mklab/workspace/iiot-eddp/Vitis/zcu104_foc_pkg/vivado/output/temp/vv/k26_foc.gen/sources_1/bd/design_1/ip/design_1_psu_0/design_1_psu_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_psu_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/mklab/workspace/iiot-eddp/Vitis/zcu104_foc_pkg/vivado/output/temp/vv/k26_foc.srcs/sources_1/bd/design_1/ip/design_1_psu_0/design_1_psu_0.xci
# IP: The module: 'design_1_psu_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mklab/workspace/iiot-eddp/Vitis/zcu104_foc_pkg/vivado/output/temp/vv/k26_foc.gen/sources_1/bd/design_1/ip/design_1_psu_0/design_1_psu_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_psu_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/mklab/workspace/iiot-eddp/Vitis/zcu104_foc_pkg/vivado/output/temp/vv/k26_foc.gen/sources_1/bd/design_1/ip/design_1_psu_0/design_1_psu_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_psu_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
