// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module foc_frontend_PI_control_ap_fixed_32_18_5_3_0_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ref,
        val_r,
        KP,
        KI,
        ierr_V_i,
        ierr_V_o,
        ierr_V_o_ap_vld,
        ap_return
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] ref;
input  [31:0] val_r;
input  [27:0] KP;
input  [18:0] KI;
input  [31:0] ierr_V_i;
output  [31:0] ierr_V_o;
output   ierr_V_o_ap_vld;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] ierr_V_o;
reg ierr_V_o_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [53:0] trunc_ln1245_fu_142_p1;
reg   [53:0] trunc_ln1245_reg_305;
reg   [0:0] tmp_reg_310;
reg   [45:0] trunc_ln1201_4_reg_315;
wire  signed [31:0] add_ln712_fu_92_p2;
wire  signed [31:0] err_V_fu_82_p2;
wire   [50:0] r_V_16_fu_126_p2;
wire  signed [58:0] sext_ln1245_fu_132_p1;
wire   [58:0] r_V_fu_112_p2;
wire   [58:0] ret_V_fu_136_p2;
wire    ap_CS_fsm_state2;
wire   [53:0] sub_ln1201_fu_164_p2;
wire   [45:0] trunc_ln1201_3_fu_169_p4;
wire   [45:0] sub_ln1201_2_fu_179_p2;
wire   [45:0] select_ln1201_fu_185_p3;
wire   [31:0] x_V_fu_191_p4;
wire   [31:0] p_Val2_s_fu_201_p2;
wire   [0:0] p_Result_s_fu_217_p3;
wire   [31:0] p_Result_27_fu_207_p4;
wire   [31:0] select_ln180_fu_225_p3;
wire   [0:0] icmp_ln1548_fu_239_p2;
wire   [0:0] tmp_30_fu_249_p3;
wire   [1:0] zext_ln12_fu_245_p1;
wire   [1:0] zext_ln12_14_fu_257_p1;
wire   [1:0] sub_ln12_fu_261_p2;
wire   [15:0] shl_ln740_s_fu_275_p3;
wire   [30:0] shl_ln_fu_267_p3;
wire  signed [30:0] sext_ln740_fu_283_p1;
wire   [30:0] sub_ln740_fu_287_p2;
wire   [0:0] icmp_ln1547_fu_233_p2;
wire  signed [31:0] sext_ln1547_fu_293_p1;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

foc_frontend_mul_28s_32s_59_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 28 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 59 ))
mul_28s_32s_59_1_1_U38(
    .din0(KP),
    .din1(err_V_fu_82_p2),
    .dout(r_V_fu_112_p2)
);

foc_frontend_mul_19s_32s_51_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 19 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 51 ))
mul_19s_32s_51_1_1_U39(
    .din0(KI),
    .din1(add_ln712_fu_92_p2),
    .dout(r_V_16_fu_126_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        tmp_reg_310 <= ret_V_fu_136_p2[32'd58];
        trunc_ln1201_4_reg_315 <= {{ret_V_fu_136_p2[53:8]}};
        trunc_ln1245_reg_305 <= trunc_ln1245_fu_142_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        ierr_V_o = add_ln712_fu_92_p2;
    end else begin
        ierr_V_o = ierr_V_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ierr_V_o_ap_vld = 1'b1;
    end else begin
        ierr_V_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln712_fu_92_p2 = ($signed(ierr_V_i) + $signed(err_V_fu_82_p2));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_return = ((icmp_ln1547_fu_233_p2[0:0] == 1'b1) ? sext_ln1547_fu_293_p1 : x_V_fu_191_p4);

assign err_V_fu_82_p2 = (ref - val_r);

assign icmp_ln1547_fu_233_p2 = (($signed(select_ln180_fu_225_p3) > $signed(32'd536854528)) ? 1'b1 : 1'b0);

assign icmp_ln1548_fu_239_p2 = (($signed(x_V_fu_191_p4) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign p_Result_27_fu_207_p4 = {|(1'd0), p_Val2_s_fu_201_p2[31 - 1:0]};

assign p_Result_s_fu_217_p3 = select_ln1201_fu_185_p3[32'd45];

assign p_Val2_s_fu_201_p2 = (32'd0 - x_V_fu_191_p4);

assign ret_V_fu_136_p2 = ($signed(sext_ln1245_fu_132_p1) + $signed(r_V_fu_112_p2));

assign select_ln1201_fu_185_p3 = ((tmp_reg_310[0:0] == 1'b1) ? sub_ln1201_2_fu_179_p2 : trunc_ln1201_4_reg_315);

assign select_ln180_fu_225_p3 = ((p_Result_s_fu_217_p3[0:0] == 1'b1) ? p_Result_27_fu_207_p4 : x_V_fu_191_p4);

assign sext_ln1245_fu_132_p1 = $signed(r_V_16_fu_126_p2);

assign sext_ln1547_fu_293_p1 = $signed(sub_ln740_fu_287_p2);

assign sext_ln740_fu_283_p1 = $signed(shl_ln740_s_fu_275_p3);

assign shl_ln740_s_fu_275_p3 = {{sub_ln12_fu_261_p2}, {14'd0}};

assign shl_ln_fu_267_p3 = {{sub_ln12_fu_261_p2}, {29'd0}};

assign sub_ln1201_2_fu_179_p2 = (46'd0 - trunc_ln1201_3_fu_169_p4);

assign sub_ln1201_fu_164_p2 = (54'd0 - trunc_ln1245_reg_305);

assign sub_ln12_fu_261_p2 = (zext_ln12_fu_245_p1 - zext_ln12_14_fu_257_p1);

assign sub_ln740_fu_287_p2 = ($signed(shl_ln_fu_267_p3) - $signed(sext_ln740_fu_283_p1));

assign tmp_30_fu_249_p3 = select_ln1201_fu_185_p3[32'd45];

assign trunc_ln1201_3_fu_169_p4 = {{sub_ln1201_fu_164_p2[53:8]}};

assign trunc_ln1245_fu_142_p1 = ret_V_fu_136_p2[53:0];

assign x_V_fu_191_p4 = {{select_ln1201_fu_185_p3[45:14]}};

assign zext_ln12_14_fu_257_p1 = tmp_30_fu_249_p3;

assign zext_ln12_fu_245_p1 = icmp_ln1548_fu_239_p2;

endmodule //foc_frontend_PI_control_ap_fixed_32_18_5_3_0_s
