-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity foc_frontend_PI_control_ap_fixed_48_24_5_3_0_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ref : IN STD_LOGIC_VECTOR (47 downto 0);
    val_r : IN STD_LOGIC_VECTOR (47 downto 0);
    KP : IN STD_LOGIC_VECTOR (37 downto 0);
    KI : IN STD_LOGIC_VECTOR (28 downto 0);
    ierr_V_i : IN STD_LOGIC_VECTOR (47 downto 0);
    ierr_V_o : OUT STD_LOGIC_VECTOR (47 downto 0);
    ierr_V_o_ap_vld : OUT STD_LOGIC;
    ap_return : OUT STD_LOGIC_VECTOR (47 downto 0) );
end;


architecture behav of foc_frontend_PI_control_ap_fixed_48_24_5_3_0_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_54 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010100";
    constant ap_const_lv80_0 : STD_LOGIC_VECTOR (79 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv72_0 : STD_LOGIC_VECTOR (71 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv48_0 : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv48_7FFF000000 : STD_LOGIC_VECTOR (47 downto 0) := "000000000111111111111111000000000000000000000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal r_V_fu_112_p2 : STD_LOGIC_VECTOR (84 downto 0);
    signal r_V_reg_306 : STD_LOGIC_VECTOR (84 downto 0);
    signal r_V_23_fu_126_p2 : STD_LOGIC_VECTOR (75 downto 0);
    signal r_V_23_reg_311 : STD_LOGIC_VECTOR (75 downto 0);
    signal add_ln712_fu_92_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal err_V_fu_82_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal sext_ln1245_fu_132_p1 : STD_LOGIC_VECTOR (84 downto 0);
    signal ret_V_fu_135_p2 : STD_LOGIC_VECTOR (84 downto 0);
    signal trunc_ln1245_fu_140_p1 : STD_LOGIC_VECTOR (79 downto 0);
    signal sub_ln1201_fu_152_p2 : STD_LOGIC_VECTOR (79 downto 0);
    signal trunc_ln1201_3_fu_158_p4 : STD_LOGIC_VECTOR (71 downto 0);
    signal tmp_fu_144_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln1201_2_fu_168_p2 : STD_LOGIC_VECTOR (71 downto 0);
    signal trunc_ln1201_4_fu_174_p4 : STD_LOGIC_VECTOR (71 downto 0);
    signal select_ln1201_fu_184_p3 : STD_LOGIC_VECTOR (71 downto 0);
    signal x_V_fu_192_p4 : STD_LOGIC_VECTOR (47 downto 0);
    signal p_Val2_s_fu_202_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal p_Result_s_fu_218_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_27_fu_208_p4 : STD_LOGIC_VECTOR (47 downto 0);
    signal select_ln180_fu_226_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal icmp_ln1548_fu_240_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_45_fu_250_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln12_fu_246_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln12_10_fu_258_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal sub_ln12_fu_262_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal shl_ln_fu_272_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln23_fu_268_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_46_fu_280_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_s_fu_286_p3 : STD_LOGIC_VECTOR (40 downto 0);
    signal icmp_ln1547_fu_234_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln737_fu_294_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component foc_frontend_mul_38s_48s_85_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (37 downto 0);
        din1 : IN STD_LOGIC_VECTOR (47 downto 0);
        dout : OUT STD_LOGIC_VECTOR (84 downto 0) );
    end component;


    component foc_frontend_mul_29s_48s_76_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (28 downto 0);
        din1 : IN STD_LOGIC_VECTOR (47 downto 0);
        dout : OUT STD_LOGIC_VECTOR (75 downto 0) );
    end component;



begin
    mul_38s_48s_85_1_1_U38 : component foc_frontend_mul_38s_48s_85_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 38,
        din1_WIDTH => 48,
        dout_WIDTH => 85)
    port map (
        din0 => KP,
        din1 => err_V_fu_82_p2,
        dout => r_V_fu_112_p2);

    mul_29s_48s_76_1_1_U39 : component foc_frontend_mul_29s_48s_76_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 29,
        din1_WIDTH => 48,
        dout_WIDTH => 76)
    port map (
        din0 => KI,
        din1 => add_ln712_fu_92_p2,
        dout => r_V_23_fu_126_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                r_V_23_reg_311 <= r_V_23_fu_126_p2;
                r_V_reg_306 <= r_V_fu_112_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln712_fu_92_p2 <= std_logic_vector(unsigned(ierr_V_i) + unsigned(err_V_fu_82_p2));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= 
        sext_ln737_fu_294_p1 when (icmp_ln1547_fu_234_p2(0) = '1') else 
        x_V_fu_192_p4;
    err_V_fu_82_p2 <= std_logic_vector(unsigned(ref) - unsigned(val_r));
    icmp_ln1547_fu_234_p2 <= "1" when (signed(select_ln180_fu_226_p3) > signed(ap_const_lv48_7FFF000000)) else "0";
    icmp_ln1548_fu_240_p2 <= "1" when (signed(x_V_fu_192_p4) > signed(ap_const_lv48_0)) else "0";

    ierr_V_o_assign_proc : process(ap_CS_fsm_state1, ierr_V_i, add_ln712_fu_92_p2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            ierr_V_o <= add_ln712_fu_92_p2;
        else 
            ierr_V_o <= ierr_V_i;
        end if; 
    end process;


    ierr_V_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ierr_V_o_ap_vld <= ap_const_logic_1;
        else 
            ierr_V_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    
    p_Result_27_fu_208_p4_proc : process(p_Val2_s_fu_202_p2)
    begin
        p_Result_27_fu_208_p4 <= p_Val2_s_fu_202_p2;
        p_Result_27_fu_208_p4(47) <= ap_const_lv1_0(0);
    end process;

    p_Result_s_fu_218_p3 <= select_ln1201_fu_184_p3(71 downto 71);
    p_Val2_s_fu_202_p2 <= std_logic_vector(unsigned(ap_const_lv48_0) - unsigned(x_V_fu_192_p4));
    ret_V_fu_135_p2 <= std_logic_vector(signed(sext_ln1245_fu_132_p1) + signed(r_V_reg_306));
    select_ln1201_fu_184_p3 <= 
        sub_ln1201_2_fu_168_p2 when (tmp_fu_144_p3(0) = '1') else 
        trunc_ln1201_4_fu_174_p4;
    select_ln180_fu_226_p3 <= 
        p_Result_27_fu_208_p4 when (p_Result_s_fu_218_p3(0) = '1') else 
        x_V_fu_192_p4;
        sext_ln1245_fu_132_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_23_reg_311),85));

        sext_ln23_fu_268_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln12_fu_262_p2),17));

        sext_ln737_fu_294_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_s_fu_286_p3),48));

    shl_ln_fu_272_p3 <= (sub_ln12_fu_262_p2 & ap_const_lv15_0);
    sub_ln1201_2_fu_168_p2 <= std_logic_vector(unsigned(ap_const_lv72_0) - unsigned(trunc_ln1201_3_fu_158_p4));
    sub_ln1201_fu_152_p2 <= std_logic_vector(unsigned(ap_const_lv80_0) - unsigned(trunc_ln1245_fu_140_p1));
    sub_ln12_fu_262_p2 <= std_logic_vector(unsigned(zext_ln12_fu_246_p1) - unsigned(zext_ln12_10_fu_258_p1));
    tmp_45_fu_250_p3 <= select_ln1201_fu_184_p3(71 downto 71);
    tmp_46_fu_280_p2 <= std_logic_vector(unsigned(shl_ln_fu_272_p3) - unsigned(sext_ln23_fu_268_p1));
    tmp_fu_144_p3 <= ret_V_fu_135_p2(84 downto 84);
    tmp_s_fu_286_p3 <= (tmp_46_fu_280_p2 & ap_const_lv24_0);
    trunc_ln1201_3_fu_158_p4 <= sub_ln1201_fu_152_p2(79 downto 8);
    trunc_ln1201_4_fu_174_p4 <= ret_V_fu_135_p2(79 downto 8);
    trunc_ln1245_fu_140_p1 <= ret_V_fu_135_p2(80 - 1 downto 0);
    x_V_fu_192_p4 <= select_ln1201_fu_184_p3(71 downto 24);
    zext_ln12_10_fu_258_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_45_fu_250_p3),2));
    zext_ln12_fu_246_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(icmp_ln1548_fu_240_p2),2));
end behav;
